[workspace]
members = ["crates/*"]

[profile.release]
opt-level = 3
lto = "fat"

[profile.release-lite]
inherits = "release"
opt-level = 2
lto = "thin"

[profile.debug-opt]
inherits = "release"
debug = 2
debug-assertions = true
incremental = true

[profile.heroku]
inherits = "release"
# Uncomment below if build performance declines
# opt-level = "z"
# lto = false
