[package]
name = "metaplex-indexer"
version = "0.1.0"
authors = [
  "ryans <ryans@holaplex.com>",
]
edition = "2021"
description = "Indexer write worker for caching Metaplex data"
documentation = "https://docs.rs/metaplex-indexer"
readme = "../../README.md"
repository = "https://github.com/holaplex/metaplex-indexer"
license = "MIT OR Apache-2.0"
keywords = ["solana", "metaplex", "holaplex", "web3"]
categories = ["cryptography::cryptocurrencies", "web-programming"]

[dependencies]
baby-pool = "0.2.0"
reqwest = "0.11.6"
serde = { version = "1.0.130", features = ["derive"] }
solana-client = "1.8.3"
solana-sdk = "1.8.3"
tokio = { version = "1.13.0", features = ["rt"] }

[dependencies.indexer-core]
package = "metaplex-indexer-core"
version = "=0.1.0"
path = "../core"

