[package]
name = "metaplex-indexer"
version = "0.0.0"
edition = "2021"

[dependencies]
solana-client = "1.8.3"
solana-sdk = "1.8.3"

[dependencies.indexer-core]
package = "metaplex-indexer-core"
version = "=0.0.0"
path = "../core"

