[package]
name = "metaplex-indexer-rpc"
version = "0.0.0"
edition = "2021"

[dependencies]
# Add dependencies

[dependencies.indexer-core]
package = "metaplex-indexer-core"
version = "=0.0.0"
path = "../core"

