[package]
name = "metaplex-indexer-core"
version = "0.1.0"
authors = [
  "ryans <ryans@holaplex.com>",
]
edition = "2021"
description = "Core components for metaplex-indexer and metaplex-indexer-rpc"
documentation = "https://docs.rs/metaplex-indexer-core"
readme = "../../README.md"
repository = "https://github.com/holaplex/metaplex-indexer"
license = "MIT OR Apache-2.0"
keywords = ["solana", "metaplex", "holaplex", "web3"]
categories = ["cryptography::cryptocurrencies", "web-programming"]

[dependencies]
# Basic utilities
anyhow = "1.0.45"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
rand = "0.8.4"

# Concurrency
dashmap = "4.0.2"
seahash = "4.1.0"

# ORM
diesel = "1.4.8"

# Solana
solana-sdk = "1.8.3"

