[package]
name = "metaplex-indexer-core"
version = "0.0.0"
edition = "2021"

[dependencies]
# Basic utilities
anyhow = "1.0.45"
dispose = "0.3.1"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.14"
rand = "0.8.4"

# Concurrency
crossbeam = "0.8.1"
dashmap = "4.0.2"
num_cpus = "1.13.0"
parking_lot = "0.11.2"
seahash = "4.1.0"

# ORM
diesel = "1.4.8"

# Solana
solana-sdk = "1.8.3"

